In [2]:
import pandas as pd

In [41]:
df=pd.read_csv("Osiris_Export_3_utf8_formed.csv",sep=",")
df=df.drop(columns=["Mark","Indep. Ind."])

In [42]:
df

,Number of employees Last avail. yr,Cash & Cash Equivalents at the End of Period th USD Last avail. yr,Cash & Cash Equivalents at the End of Period th USD Year - 1,Cash & Cash Equivalents at the End of Period th USD Year - 2,Cash & Cash Equivalents at the End of Period th USD Year - 3,Cash & Cash Equivalents at the End of Period th USD Year - 4,Cash & Cash Equivalents at the End of Period th USD Year - 5,Cash & Cash Equivalents at the Beginning of Period th USD Last avail. yr,Cash & Cash Equivalents at the Beginning of Period th USD Year - 1,Cash & Cash Equivalents at the Beginning of Period th USD Year - 2,...,Ordinary dividends th USD Year - 3.4,Ordinary dividends th USD Year - 4.4,Ordinary dividends th USD Year - 5.4,Dividend share capital other th USD Last avail. yr.4,Dividend share capital other th USD Year - 1.4,Dividend share capital other th USD Year - 2.4,Dividend share capital other th USD Year - 3.4,Dividend share capital other th USD Year - 4.4,Dividend share capital other th USD Year - 5.4,Moody's Long-Term Rating
0,20000,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,89800,69800,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Baa2
1,28630,2625975,2168147,1966709,1116348,1237301,2244832,1893866,2311230,818837,...,0,355672,370834,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Ba2
2,14500,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,149900,145400,132500,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Baa2
3,25532,7293492,7812315,8377941,6322423,4574432,2925034,8014049,8957547,6367208,...,222407,169826,111612,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Ca
4,n.a.,2237610,2407285,2578211,1124624,1246558,1378521,2072642,2339375,1184203,...,288141,283624,272232,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Baa1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,2256,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,0,0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Ba3
267,5000,427118,354850,851012,1069214,110865,116149,325161,932232,1061020,...,121722,0,0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Baa2
268,15018,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,1236900,1082300,456100,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Baa1
269,30106,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,17300,17100,16900,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Aa2
270,13400,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,525,52992,62933,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Ba3

In [43]:
y=df["Moody's Long-Term Rating"]

In [44]:
nums=df.drop(["Moody's Long-Term Rating"],axis=1)

In [45]:
import numpy as np
nums=nums.replace("n.a.",np.float32(0.0))
nums=nums.replace(",","")

In [46]:
nums=nums.astype("float32")

In [47]:
y

0      Baa2
1       Ba2
2      Baa2
3        Ca
4      Baa1
       ...
266     Ba3
267    Baa2
268    Baa1
269     Aa2
270     Ba3
Name: Moody's Long-Term Rating, Length: 271, dtype: object

In [48]:
y.value_counts()

Baa1       58
Baa2       55
A3         31
Baa3       30
Ba1        18
Ba3        14
A2         14
Ba2        11
A1          8
Aa3         7
B2          6
B3          3
Ca          3
(P)Baa2     2
Caa1        2
B1          2
Aaa         2
Aa2         2
Caa3        1
(P)A1       1
Caa2        1
Name: Moody's Long-Term Rating, dtype: int64

In [49]:
mapping = {
    'Aaa': 21, 'Aa1': 20, 'Aa2': 19, 'Aa3': 18,
    'A1': 17, 'A2': 16, 'A3': 15,
    'Baa1': 14, 'Baa2': 13, 'Baa3': 12,
    'Ba1': 11, 'Ba2': 10, 'Ba3': 9,
    'B1': 8, 'B2': 7, 'B3': 6,
    'Caa1': 5, 'Caa2': 4, 'Caa3': 3,
    'Ca': 2, 'C': 1, 'WR': 0,
    '(P)Aaa': 21.25, '(P)Aa1': 20.25, '(P)Aa2': 19.25, '(P)Aa3': 18.25,
    '(P)A1': 17.25, '(P)A2': 16.25, '(P)A3': 15.25,
    '(P)Baa1': 14.25, '(P)Baa2': 13.25, '(P)Baa3': 12.25,
    '(P)Ba1': 11.25, '(P)Ba2': 10.25, '(P)Ba3': 9.25,
    '(P)B1': 8.25, '(P)B2': 7.25, '(P)B3': 6.25,
    '(P)Caa1': 5.25, '(P)Caa2': 4.25, '(P)Caa3': 3.25,
    '(P)Ca': 2.25, '(P)C': 1.25, '(P)WR': 0.25,
    '(M)Aaa': 20.75, '(M)Aa1': 19.75, '(M)Aa2': 18.75, '(M)Aa3': 17.75,
    '(M)A1': 16.75, '(M)A2': 15.75, '(M)A3': 14.75,
    '(M)Baa1': 13.75, '(M)Baa2': 12.75, '(M)Baa3': 11.75,
    '(M)Ba1': 10.75, '(M)Ba2': 9.75, '(M)Ba3': 8.75,
    '(M)B1': 7.75, '(M)B2': 6.75, '(M)B3': 5.75,
    '(M)Caa1': 4.75, '(M)Caa2': 3.75, '(M)Caa3': 2.75,
    '(M)Ca': 1.75, '(M)C': 0.75, '(M)WR': -0.25}

In [50]:
y_formed= y.map(mapping)

In [51]:
y_formed

0      13.0
1      10.0
2      13.0
3       2.0
4      14.0
       ...
266     9.0
267    13.0
268    14.0
269    19.0
270     9.0
Name: Moody's Long-Term Rating, Length: 271, dtype: float64

In [52]:
merged_df = pd.concat([nums,y_formed], axis=1)

In [53]:
merged_df

,Number of employees Last avail. yr,Cash & Cash Equivalents at the End of Period th USD Last avail. yr,Cash & Cash Equivalents at the End of Period th USD Year - 1,Cash & Cash Equivalents at the End of Period th USD Year - 2,Cash & Cash Equivalents at the End of Period th USD Year - 3,Cash & Cash Equivalents at the End of Period th USD Year - 4,Cash & Cash Equivalents at the End of Period th USD Year - 5,Cash & Cash Equivalents at the Beginning of Period th USD Last avail. yr,Cash & Cash Equivalents at the Beginning of Period th USD Year - 1,Cash & Cash Equivalents at the Beginning of Period th USD Year - 2,...,Ordinary dividends th USD Year - 3.4,Ordinary dividends th USD Year - 4.4,Ordinary dividends th USD Year - 5.4,Dividend share capital other th USD Last avail. yr.4,Dividend share capital other th USD Year - 1.4,Dividend share capital other th USD Year - 2.4,Dividend share capital other th USD Year - 3.4,Dividend share capital other th USD Year - 4.4,Dividend share capital other th USD Year - 5.4,Moody's Long-Term Rating
0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,89800.0,69800.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0
1,28630.0,2625975.0,2168147.0,1966709.0,1116348.0,1237301.0,2244832.0,1893866.0,2311230.0,818837.0,...,0.0,355672.0,370834.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
2,14500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,149900.0,145400.0,132500.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0
3,25532.0,7293492.0,7812315.0,8377941.0,6322423.0,4574432.0,2925034.0,8014049.0,8957547.0,6367208.0,...,222407.0,169826.0,111612.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
4,0.0,2237610.0,2407285.0,2578211.0,1124624.0,1246558.0,1378521.0,2072642.0,2339375.0,1184203.0,...,288141.0,283624.0,272232.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,2256.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
267,5000.0,427118.0,354850.0,851012.0,1069214.0,110865.0,116149.0,325161.0,932232.0,1061020.0,...,121722.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0
268,15018.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1236900.0,1082300.0,456100.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0
269,30106.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,17300.0,17100.0,16900.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
270,13400.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,525.0,52992.0,62933.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0

In [54]:
merged_df.to_csv('data4.csv', index=False)

In [ ]:
import pandas as pd

df = pd.read_csv('test4.txt', sep='\t', encoding='utf-16', header=None)
df = df.applymap(lambda x: str(x).replace(',', ''))  # カンマを削除
df