In [179]:
import pandas as pd

In [180]:
df=pd.read_csv("Osiris_Export_1(tlansed).csv")

In [181]:
df

,Mark,Company name,Country code (incorp),GICS code,Cons. code,Operating Rev./ Turnover th USD Last avail. yr,Number of employees Last avail. yr,Indep. Ind.,ISIN Number,Cash & Cash Equivalents at the End of Period th USD Last avail. yr,...,Ordinary dividends th USD Year - 3.4,Ordinary dividends th USD Year - 4.4,Ordinary dividends th USD Year - 5.4,Dividend share capital other th USD Last avail. yr.4,Dividend share capital other th USD Year - 1.4,Dividend share capital other th USD Year - 2.4,Dividend share capital other th USD Year - 3.4,Dividend share capital other th USD Year - 4.4,Dividend share capital other th USD Year - 5.4,Moody's Long-Term Rating
0,1,WALMART INC.,US,30101040.0,C1,611289000,2100000,B+,US9311421039,n.a.,...,6048000,6102000,6124000,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Aa2
1,2,SAUDI ARABIAN OIL COMPANY SAUDI JOINT STOCK CO...,SA,10102010.0,C1,604366165,70496,D,SA14TG012N13,60279203,...,3936000,0,0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,A1
2,3,"AMAZON.COM, INC.",US,25503030.0,C1,513983000,1541000,A+,US0231351067,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,A1
3,4,CHINA PETROLEUM & CHEMICAL CORPORATION,CN,10102010.0,C1,431414669,385691,D,CNE0000018G1,17046025,...,7420108,9296486,4337823,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,A1
4,5,PETROCHINA COMPANY LIMITED,CN,10102010.0,C1,412368455,417173,D,CNE1000003W8,21472592,...,4775135,3653941,1562059,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,267,CHS INC.,US,30202010.0,C1,47791666,10014,A-,US12542R2094,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,NaN
267,268,GREAT-WEST LIFECO INC.,CA,40301020.0,C1,47576271,n.a.,D,CA39138C1068,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,NaN
268,269,BANDAR ABBAS OIL REFINING COMPANY PUBLIC JOINT...,IR,NaN,C1,47495404,3666,B+,IRO1PNBA0003,188765,...,558571,201097,276664,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,NaN
269,270,"GOLDMAN SACHS GROUP, INC",US,40203020.0,C2,47398000,48500,A+,US38141G1040,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,NaN
270,271,POWER FINANCIAL CORP,CA,40301020.0,C1,47376316,n.a.,D,CA73927C1005,7239580,...,704495,906825,935017,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,NaN

In [182]:
df=df.dropna(subset=["Moody's Long-Term Rating"])

In [183]:
df.dtypes

Mark                                                int64
Company name                                       object
Country code (incorp)                              object
GICS code                                         float64
Cons. code                                         object
                                                   ...
Dividend share capital other th USD Year - 2.4     object
Dividend share capital other th USD Year - 3.4     object
Dividend share capital other th USD Year - 4.4     object
Dividend share capital other th USD Year - 5.4     object
Moody's Long-Term Rating                           object
Length: 3682, dtype: object

In [184]:
df = df.drop(labels=["Country code (incorp)",'Company name', 'Mark','GICS code',"Operating Rev./ Turnover th USD Last avail. yr","ISIN Number"], axis=1)

In [185]:
df

,Cons. code,Number of employees Last avail. yr,Indep. Ind.,Cash & Cash Equivalents at the End of Period th USD Last avail. yr,Cash & Cash Equivalents at the End of Period th USD Year - 1,Cash & Cash Equivalents at the End of Period th USD Year - 2,Cash & Cash Equivalents at the End of Period th USD Year - 3,Cash & Cash Equivalents at the End of Period th USD Year - 4,Cash & Cash Equivalents at the End of Period th USD Year - 5,Cash & Cash Equivalents at the Beginning of Period th USD Last avail. yr,...,Ordinary dividends th USD Year - 3.4,Ordinary dividends th USD Year - 4.4,Ordinary dividends th USD Year - 5.4,Dividend share capital other th USD Last avail. yr.4,Dividend share capital other th USD Year - 1.4,Dividend share capital other th USD Year - 2.4,Dividend share capital other th USD Year - 3.4,Dividend share capital other th USD Year - 4.4,Dividend share capital other th USD Year - 5.4,Moody's Long-Term Rating
0,C1,2100000,B+,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,6048000,6102000,6124000,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Aa2
1,C1,70496,D,60279203,79887737,55261870,47388269,48840536,21664534,79887737,...,3936000,0,0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,A1
2,C1,1541000,A+,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,A1
3,C1,385691,D,17046025,13398674,8650064,16331826,17387124,17909581,13744663,...,7420108,9296486,4337823,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,A1
5,C1,62000,A+,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,14652000,13798000,13001000,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Aa2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,C1,n.a.,D,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,30182,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,WR
262,C1,n.a.,C,213876,1843761,617000,1088000,328000,917000,1711010,...,5044000,4772000,2918000,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,WR
263,C1,129700,A+,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,180000,188000,198000,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,B2
264,C1,129700,D,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,Ba3
265,C2,n.a.,A+,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,(P)A2

In [186]:
y=df["Moody's Long-Term Rating"]

In [187]:
categories=df[["Cons. code","Indep. Ind."]]

In [188]:
nums=df.drop(["Moody's Long-Term Rating","Cons. code","Indep. Ind."],axis=1)

In [189]:
import numpy as np
nums=nums.replace("n.a.",np.float32(0.0))
nums=nums.replace(",","")

In [190]:
nums=nums.astype("float32")

In [191]:
categories=pd.get_dummies(categories)

In [192]:
categories=categories.astype('float32')

In [193]:
y

0        Aa2
1         A1
2         A1
3         A1
5        Aa2
       ...
261       WR
262       WR
263       B2
264      Ba3
265    (P)A2
Name: Moody's Long-Term Rating, Length: 202, dtype: object

In [194]:
y.value_counts()

Baa1     32
Baa2     30
A2       24
A3       23
A1       23
WR       16
Baa3     15
Aa2      11
Aa3       8
Ba3       4
Ba2       4
Aaa       4
Caa2      2
Ba1       1
(P)A1     1
B1        1
Aa1       1
B2        1
(P)A2     1
Name: Moody's Long-Term Rating, dtype: int64

In [195]:
mapping = {
    'Aaa': 21, 'Aa1': 20, 'Aa2': 19, 'Aa3': 18,
    'A1': 17, 'A2': 16, 'A3': 15,
    'Baa1': 14, 'Baa2': 13, 'Baa3': 12,
    'Ba1': 11, 'Ba2': 10, 'Ba3': 9,
    'B1': 8, 'B2': 7, 'B3': 6,
    'Caa1': 5, 'Caa2': 4, 'Caa3': 3,
    'Ca': 2, 'C': 1, 'WR': 0,
    '(P)Aaa': 21.25, '(P)Aa1': 20.25, '(P)Aa2': 19.25, '(P)Aa3': 18.25,
    '(P)A1': 17.25, '(P)A2': 16.25, '(P)A3': 15.25,
    '(P)Baa1': 14.25, '(P)Baa2': 13.25, '(P)Baa3': 12.25,
    '(P)Ba1': 11.25, '(P)Ba2': 10.25, '(P)Ba3': 9.25,
    '(P)B1': 8.25, '(P)B2': 7.25, '(P)B3': 6.25,
    '(P)Caa1': 5.25, '(P)Caa2': 4.25, '(P)Caa3': 3.25,
    '(P)Ca': 2.25, '(P)C': 1.25, '(P)WR': 0.25,
    '(M)Aaa': 20.75, '(M)Aa1': 19.75, '(M)Aa2': 18.75, '(M)Aa3': 17.75,
    '(M)A1': 16.75, '(M)A2': 15.75, '(M)A3': 14.75,
    '(M)Baa1': 13.75, '(M)Baa2': 12.75, '(M)Baa3': 11.75,
    '(M)Ba1': 10.75, '(M)Ba2': 9.75, '(M)Ba3': 8.75,
    '(M)B1': 7.75, '(M)B2': 6.75, '(M)B3': 5.75,
    '(M)Caa1': 4.75, '(M)Caa2': 3.75, '(M)Caa3': 2.75,
    '(M)Ca': 1.75, '(M)C': 0.75, '(M)WR': -0.25}

In [196]:
y_formed= y.map(mapping)

In [197]:
y_formed

0      19.00
1      17.00
2      17.00
3      17.00
5      19.00
       ...
261     0.00
262     0.00
263     7.00
264     9.00
265    16.25
Name: Moody's Long-Term Rating, Length: 202, dtype: float64

In [218]:
merged_df = pd.concat([nums,categories], axis=1)

In [219]:
merged_df

,Number of employees Last avail. yr,Cash & Cash Equivalents at the End of Period th USD Last avail. yr,Cash & Cash Equivalents at the End of Period th USD Year - 1,Cash & Cash Equivalents at the End of Period th USD Year - 2,Cash & Cash Equivalents at the End of Period th USD Year - 3,Cash & Cash Equivalents at the End of Period th USD Year - 4,Cash & Cash Equivalents at the End of Period th USD Year - 5,Cash & Cash Equivalents at the Beginning of Period th USD Last avail. yr,Cash & Cash Equivalents at the Beginning of Period th USD Year - 1,Cash & Cash Equivalents at the Beginning of Period th USD Year - 2,...,Dividend share capital other th USD Year - 5.4,Cons. code_C1,Cons. code_C2,Indep. Ind._-,Indep. Ind._A+,Indep. Ind._B+,Indep. Ind._C,Indep. Ind._C+,Indep. Ind._D,Indep. Ind._U
0,2100000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,70496.0,60279204.0,79887736.0,55261872.0,47388268.0,48840536.0,21664534.0,79887736.0,55261872.0,47388268.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1541000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,385691.0,17046024.0,13398674.0,8650064.0,16331826.0,17387124.0,17909580.0,13744663.0,9248496.0,16019321.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,62000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
262,0.0,213876.0,1843761.0,617000.0,1088000.0,328000.0,917000.0,1711010.0,0.0,1088000.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
263,129700.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
264,129700.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
265,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [220]:
from sklearn.preprocessing import StandardScaler

# DataFrameの全体を正規化
scaler = StandardScaler()
merged_df = pd.DataFrame(scaler.fit_transform(merged_df), columns=merged_df.columns)

In [221]:
merged_df.dtypes

Number of employees Last avail. yr                                    float32
Cash & Cash Equivalents at the End of Period th USD Last avail. yr    float32
Cash & Cash Equivalents at the End of Period th USD Year - 1          float32
Cash & Cash Equivalents at the End of Period th USD Year - 2          float32
Cash & Cash Equivalents at the End of Period th USD Year - 3          float32
                                                                       ...
Indep. Ind._B+                                                        float32
Indep. Ind._C                                                         float32
Indep. Ind._C+                                                        float32
Indep. Ind._D                                                         float32
Indep. Ind._U                                                         float32
Length: 3682, dtype: object

In [222]:
learn=merged_df[:150]
test=merged_df[150:]

In [223]:
laern_y=y_formed[:150].values
laern_x=learn.values

In [224]:
np.mean(laern_y)

14.041666666666666

In [233]:
test_y=y_formed[150:].values
test_x=test.values

In [234]:
laern_x

array([[ 9.089131  , -0.6671176 , -0.6421409 , ..., -0.1894662 ,
        -0.5123475 , -0.07053456],
       [-0.33127317,  4.5618095 ,  5.9369626 , ..., -0.1894662 ,
         1.9518001 , -0.07053456],
       [ 6.4944057 , -0.6671176 , -0.6421409 , ..., -0.1894662 ,
        -0.5123475 , -0.07053456],
       ...,
       [-0.54941577, -0.6671176 , -0.6421409 , ..., -0.1894662 ,
        -0.5123475 , -0.07053456],
       [ 2.688189  ,  0.01728698,  0.03054381, ..., -0.1894662 ,
        -0.5123475 , -0.07053456],
       [-0.6584964 , -0.01828581, -0.40451482, ..., -0.1894662 ,
        -0.5123475 , -0.07053456]], dtype=float32)

In [235]:
#成型官僚
#tensorflowで実験

In [236]:
import tensorflow as tf

In [238]:
# モデルの構築
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_dim=laern_x.shape[1]),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

# モデルのコンパイル
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

# モデルの学習
history = model.fit(laern_x, laern_y, epochs=5, batch_size=32, validation_split=0.1)

# テストデータでの評価
test_loss, test_mae = model.evaluate(test_x, test_y)
print('Test MAE:', test_mae)

Epoch 1/5
5/5 [==============================] - 4s 227ms/step - loss: 165.0028 - mae: 12.1540 - val_loss: 76.3813 - val_mae: 7.4692
Epoch 2/5
5/5 [==============================] - 0s 41ms/step - loss: 94.4395 - mae: 7.3348 - val_loss: 99.1176 - val_mae: 8.6344
Epoch 3/5
5/5 [==============================] - 0s 43ms/step - loss: 64.5616 - mae: 6.5237 - val_loss: 64.9626 - val_mae: 6.6552
Epoch 4/5
5/5 [==============================] - 0s 44ms/step - loss: 42.9974 - mae: 5.2771 - val_loss: 43.5472 - val_mae: 5.2594
Epoch 5/5
5/5 [==============================] - 0s 38ms/step - loss: 34.4982 - mae: 4.7372 - val_loss: 39.5239 - val_mae: 5.1280
2/2 [==============================] - 0s 10ms/step - loss: 68.7120 - mae: 6.8478
Test MAE: 6.847812175750732